# Generated by Django 4.2 on 2023-05-07 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blog',
            name='updated_at',
        ),
        migrations.AlterField(
            model_name='blog',
            name='cover_image',
            field=models.ImageField(upload_to='uploads/cover_images\\20230507153726_'),
        ),
        migrations.AlterField(
            model_name='blogpost',
            name='image',
            field=models.ImageField(upload_to='uploads/post_images\\20230507153726_'),
        ),
    ]
