# Generated by Django 4.2 on 2023-05-07 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogapp', '0002_remove_blog_updated_at_alter_blog_cover_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='cover_image',
            field=models.ImageField(upload_to='uploads/cover_images/20230507214723_'),
        ),
        migrations.AlterField(
            model_name='blogpost',
            name='image',
            field=models.ImageField(upload_to='uploads/post_images/20230507214723_'),
        ),
    ]
