# Generated by Django 4.2 on 2023-05-07 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogapp', '0003_alter_blog_cover_image_alter_blogpost_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='cover_image',
            field=models.ImageField(upload_to='uploads/cover_images/20230507214738_'),
        ),
        migrations.AlterField(
            model_name='blogpost',
            name='image',
            field=models.ImageField(upload_to='uploads/post_images/20230507214738_'),
        ),
    ]
